### ISSUE TITLE
Adding Windows Phone and Store support

### ISSUE THREAD

**Issue by SaviorXTanren** [kamegami13/MonsterHunter4UDatabase#113]
Hey, I've wrote an app database app for MH3 on the Windows Phone and am currently working on a port of it to the Windows Store: https://www.windowsphone.com/en-us/store/app/mh3u-g-dex/65cc81b5-a7d7-416b-a444-bc888793c9e4

My app was written in conjuction with Ping of Ping's Dex. I've gotten requests for a MH4 version, however Ping has been very resistant with giving me access to the MH4 data. Without it, I obviously can't make the app. I was wondering if you guys would be interested in partnering to create a MH4 version for the windows phone and windows store. I'd continue working on the app to completion and put it up on GitHub for public contribution. I would mainly just need access to the data for the app.

Let me know if you guys would be interested. Thanks!

**Comment by jaysonthepirate** [comment]
Hey! Your app looks awesome! All our stuff is obviously open source buy right now lives in a google sheets doc. You'll have to ask Kamegami for access.

Also Microsoft announced that they are planning on releasing a support library that mimics all the Android functions. So theoretically porting should be easier if you decide to go that route.

**Comment by SaviorXTanren** [comment]
Awesome, what's the best way to get in contact with him?

I actually know about that as well, I work for Microsoft as a software developer. :) I don't know exactly how apps will be supported and for what platforms (phone and/or store) and when that will be. So, I view my apps as the stepping bridge to when that support is completed; in which case we can pool all of our efforts into one app!

**Comment by SaviorXTanren** [comment]
Hopefully he'll tagging him will be good enough. @kamegami13

**Comment by jaysonthepirate** [comment]
Yeah tagging should be fine. We're all hooked up via slack so he'll definitely see it. Send me your email and I'll send you an invite.

**Comment by SaviorXTanren** [comment]
Sounds good, email is saviorxtanren@gmail.com
