### ISSUE TITLE
Chosen items won't show up (Set builder)

### ISSUE THREAD

**Issue by KushalaDankora** [kamegami13/MonsterHunter4UDatabase#120]
Hi, my phone is HTC Desire 610, Android 4.4.2. Armor pieces won't show up after selecting them for the armor builder, skills also won't show up for the Talisman's skill selection.

**Comment by jaysonthepirate** [comment]
This is a known issue with Android versions less than 5.0. A fix is in the current github build but hasn't been pushed to the play store yet. I'm closing this issue since it's been resolved.
