### ISSUE TITLE
Pressing Back while on Weapon Detail view returns to main menu

### ISSUE THREAD

**Issue by alxcyl** [kamegami13/MonsterHunter4UDatabase#24]
1. From the main menu, click weapon.
2. Click a weapon type, e.g. Hammer
3. Click a weapon of choice
4. Press back

Pressing back should return you to weapons list instead of main menu

**Comment by alxcyl** [comment]
It apparently happens to all kinds of list, be it armor, quedt, item, map... all lists.

**Comment by mmangliers** [comment]
It's implemented as a home button, which is unfortunate and confusing. Use the android back button to return normally, and the top bar button to return to home. We're working on a more intuitive interface.

**Comment by alxcyl** [comment]
I actually noticed that a few hours after submitting this issue. If it's intended then I have no more issues with it.
