### ISSUE TITLE
Possible overhaul of the Weapons Interface?

### ISSUE THREAD

**Issue by zachdayz** [kamegami13/MonsterHunter4UDatabase#31]
Currently, the weapons list is unfortunately difficult to navigate - I feel that using the "-" character is an inefficient way to represent hierarchical relationships. Perhaps we could implement a tree-viewer interface of some sort similar to the one that Ping's MH4G DB for Windows has?

**Comment by mmangliers** [comment]
This is planned, only reason we used the dashes is because we're using the old MH3U database as our base. They didn't implement any form of trees, so we used the dashes for a quick and dirty display until we implement expandable trees. Massive UI overhauls are in the works.

**Comment by zachdayz** [comment]
If I may ask, what sort of plans are they? I would love to get involved.
